### ISSUE TITLE
Warning messages in logs

### ISSUE THREAD

**Issue by 7185** [Mariusmssj/harbour-vlc-remote#1]
Hey, thanks for this app, it's really great!
I don't know if you still maintain it, but I was wondering why my phone battery was draining faster than usual when using it and noticed the `systemd-journald` process taking some CPU%. It looks like for some reason, the journal is flooded with the same message:

`[W] unknown:156 - file:///usr/share/harbour-vlc_remote/qml/pages/FirstPage.qml:156: TypeError: Cannot read property 'fullscreen' of undefined`

I'm not even sure that's the real reason for my battery drain, or if you can fix this… The fullscreen button works fine by the way.

**Comment by Mariusmssj** [comment]
Hi there,

I still fix bugs if people report any :) This one I do not know what is caused. The full-screen is using a custom icon made by me and it's bundled in with the application I guess that's why it could be showing it. If your battery drains too quickly you can change sync time from 1 second to 2, 5, 10 see if that helps if not I will taee a look further into the issue.

**Comment by 7185** [comment]
Even if I put "never", the issue is still here. I think the error appears much more frequently than every second. It only appears when the connection is successful though.
After looking at your code, it looks like the updateXML() function is called every 50ms, so I tried to inscrease that value to 5000 in the qml file and the messages are indeed logged every 5 seconds.
I don't know if changing that value made any sense at all but it's much more bearable now!

**Comment by Mariusmssj** [comment]
Oh bummer I do apologise the code on github is really old :( I will set the thing up again and push the new code(I don't really use github). As I vaguely remember something about this. But thanks for pointing it out, as I have said in the readme file this is not a very well written app and I am sorry.

**Comment by 7185** [comment]
No problem, this is a great app.
My guess is that you just need to be sure that `element` is defined before using the `fullscreen` attribute and others. I wish I could help more, but my laptop is too old for Sailfish OS development, so I know nothing about it…
Thank you anyway, my power consumption is back to normal now :)

**Comment by Mariusmssj** [comment]
Ok then, This weekend I will set the github application again to be able to push new code and look into getting the element fixed. And big thanks for finding this, if you find anything else that looks odd let me know :) I will let you know once I upload new code here and fix the issue :)

**Comment by Mariusmssj** [comment]
OK I have pushed the new updated files, and will look into the problem later.

**Comment by Mariusmssj** [comment]
Hello, I've submitted a new version to openrepos and jolla store and seems like most logs should be fixed out. Let me know if you still get the issue.
