### ISSUE TITLE
error with sailfish 2.0.1.11 is disabling sync

### ISSUE THREAD

**Issue by amilcarsantos** [Mariusmssj/harbour-vlc-remote#4]
I've updated sailfishos to version 2.0.1.11 and sync ui is not working.
This error is being logged:

[W] unknown:152 - file:///usr/share/harbour-vlc_remote/qml/pages/FirstPage.qml:152: TypeError: Cannot read
property 'fullscreen' of undefined

**Comment by amilcarsantos** [comment]
sync ui is working again... closing issue

**Comment by Mariusmssj** [comment]
If you find any issues please let me know :)
