### ISSUE TITLE
Searchable playlist.

### ISSUE THREAD

**Issue by jsm222** [Mariusmssj/harbour-vlc-remote#7]
I have been looking into a  model in c++ for the play list to make it searchable.
Its to early for a pull request, so I am simply asking for some  reviews and opinions. :-)
It works okay for me at the moment (TM) not tested heavily though.
https://github.com/jsm222/harbour-vlc-remote/tree/cpp-playlist

**Comment by Mariusmssj** [comment]
Hi, I went through the stuff and it all looks great. When you are read just make  pull request and I will happy to merge this in the main branch :) Thank you for the great feature
